### ISSUE TITLE
Release v0.4.3 arm64 is not support config file

### ISSUE THREAD

**Issue by ghalambaz** [Admiral-Piett/goaws#273]
I used arm64 image for one of the projects but was not able to use the same config to create default queues
```
Local:
    Host: localhost
    Port: 4100
    LogMessages: true
    LogFile: ./goaws_messages.log
    Queues:
        - Name: myqueue-dev-1
        - Name: myqueue-dev-2
```
It didn't recognize the config file.
